### ISSUE TITLE
Inaccuracy in Search explanations

### ISSUE THREAD

**Issue by Zimmi48** [tchajed/coq-tricks#16]
`Search` with a string argument will assume that you are looking for lemmas containing this string in their name as soon as the string argument is a valid part of identifier (like `"mod"`). To look for the notation in this case, you should rather do `Search "'mod'"`.

**Comment by tchajed** [comment]
Thanks for pointing that out, I didn't realize that's how `Search` decided whether to search for notations or in the lemma name!
