### ISSUE TITLE
Trick suggestion: apply tactic to all subgoals

### ISSUE THREAD

**Issue by ComFreek** [tchajed/coq-tricks#17]
Here's one trick (credits to @Blaisorblade):

- If you have a tactic `s` that introduces multiple subgoals and a tactic `t`, then `s; t` will apply `t` to every subgoal individually. Sometimes, this will even cause `s` to backtrack:

   > E.g. "constructor; solve [eauto]" has been useful:
   > it picks not a random constructor, but one that allows solving all goals!

**Comment by anton-trunov** [comment]
Hi @ComFreek! I have a private collection of SSReflect tricks. Since there is interest in this topic, maybe it's time to brush them up and make available publicly...

**Comment by tchajed** [comment]
@anton-trunov that would be great, I'd be happy to add them here if you make them public!
